#--------------------------------------
# GitHub Action Part-1 Basics
#
#Copyleft (c) by Sergey Polyanskiy 2022
#--------------------------------------
name: My-GitHubActions-Basics

on:
  push:
    branches:
      - master
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run : echo "Hello World"
      
  my_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Deploy job"
