#---------------------------------------
# GitHub Action Part-1 Basics
#
#Copyleft (c) by Sergey Polyanskiy 2022
#---------------------------------------
name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - main
      
jobs:
  my_testing:
    runs-on: ubuntu-latestzxz
    
    steps:
    - name: Print Hello Message
      run : echo "Hello World"
      
    - name: Execute few comands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Aplication name is ${{ env.APPLICATION_NAME }}"
        
    - name: List current folder
      run: ls -la
      
    - name: Git clonr my repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run: ls -la
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is Job Level"
      VAR2: echo "Hello World from Deploy"
    
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Deploy job"
      
    - name: Print eny vars
      run: |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is Super Local Var"
      
    - name: Printing Deployment package
      run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
      
    - name: Lets test some packages
      run: aws --version
      
    - name: Lets test some packages
      run: zip --version
