#--------------------------------------
# GitHub Action Part-1 Basics
#
#Copyleft (c) by Sergey Polyanskiy 2022
#--------------------------------------
name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - main
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run : echo "Hello World"
      
    - name: Execute few comands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Aplication name is ${{ env.APPLICATION_NAME }}"
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Deploy job"
      
    - name: Printing Deployment package
      run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
